apiVersion: v1
kind: Pod
metadata:
  name: pod-pv-example1
  namespace: default
spec:
  containers:
    - image: docker.io/library/nginx
      name: pod-nginx
      volumeMounts:
        - name: test_pv11
          mountPath: "/pv/test_pv11"
  volumes:
    - name: test_pv11
      persistentVolume:
        pvName: test_pv11

