kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: dns-test-clusterip2
spec:
  selector:
    matchLabels:
      test: dns-clusterip2 
  ports:
    # Accept traffic sent to port 80
    - port: 9201
      targetPort: 10086
      protocol: tcp

