kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: dns-test-clusterip1
spec:
  selector:
    matchLabels:
      test: dns-clusterip1 
  ports:
    # Accept traffic sent to port 80
    - port: 9200
      targetPort: 10086
      protocol: tcp

