kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: clusterip-test
spec:
  selector:
    test: clusterip 
  ports:
    # Accept traffic sent to port 80
    - port: 9000
      targetPort: 3000
      protocol: tcp

