# This is a basic workflow to help you get started with Actions

name: MiniK8s CD

# Controls when the workflow will run
on:
  push:
    branches:
      - 'development*'
      - 'main'
  pull_request:
    branches:
      - 'development*'
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line command
        run: echo Hello, world!

      - name: Setup CD base environment by script
        run: sudo sh ./scripts/setup_cicd.sh  
        shell: bash
        
      - name: run go test script for CD
        run: echo "CD NOT READY!"
        shell: bash

